os_lidar_ancillary:
# camera
  traffic_light_left_camera:
    x: 0.708
    y: 1.053
    z: 1.479
    roll: -1.553
    pitch: 0.063
    yaw: -1.584
  camera1:
    x: 1.871
    y: 0.540
    z: 0.503
    roll: -1.549
    pitch: 0.077
    yaw: 1.568
rs16:
# lidar
  os_lidar_ancillary:
    x: 2.772 
    y: 1.402
    z: -1.005
    roll: 0.003
    pitch: 0.003
    yaw: 3.087
# robobus -- muti lidar
  os_lidar_fl:
    x: 1.178
    y: 0.910
    z: -0.335
    roll: 0.033 
    pitch: -0.283
    yaw: -1.934 
  os_lidar_fr:
    x: 1.167
    y: -0.980
    z: -0.341
    roll: -0.008
    pitch: -0.278
    yaw:  1.941
  os_lidar_rl:
    x: -1.160
    y: 0.899
    z: -0.344  
    roll: -0.022
    pitch:  -0.280
    yaw: -1.205
  os_lidar_rr:
    x: -1.162
    y: -0.977
    z: -0.344
    roll: 0.025
    pitch: -0.267
    yaw: 1.208
# combined navigation
  gnss:
    x: -0.37
    y: 0.0
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: 0.0