/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_top"
      pixel_format: "uyvy"
      color_format: "yuv422p"
      image_width: 1920 
      image_height: 1080
      camera_name: "camera_top"
      camera_info_url: "package://robobus_sensor_kit_launch/data/camera_top.yaml"
